name: CI - ML Service

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build containers
        run: |
          docker compose build --no-cache

      - name: Run training
        run: |
          docker compose run --rm trainer

      - name: Start API
        run: |
          docker compose up -d api
          sleep 10
          docker compose logs api
          curl -f http://localhost:8001 || exit 1